@baseUrl=http://localhost:3000

###
POST {{baseUrl}}/register
Content-Type: application/json

{
  "username": "testuser",
  "password": "testpassword"
}

###
POST {{baseUrl}}/login
Content-Type: application/json

{
  "username": "testuser",
  "password": "testpassword"
}

###
GET {{baseUrl}}/profile
Authorization: Bearer {{token}}

###
PUT {{baseUrl}}/change-password
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "oldPassword": "testpassword",
  "newPassword": "newtestpassword"
}
