= Pflichtenheft

== Beschreibung der Ausgangslage
- Die Ausgangslage des Projektes bestand in der Situation, wo Stationsleiter nicht alle Information von alle Rennen in ihren Gehirnen speichern können.

== Ist-Zustand
- Das Dashboard ist ein Mittel für Stationsleiter um Informationen über die Rennen schnell und einfach zu bekommen.
- Die bestehenden Systemplattformen werden die Personalrechner von den Stationsleitern sein.
- Das Dashboard wird auf einer Website Live Informationen streamen können und Stationsleiter können diese auch vergleichen.

== Zielsetzung
- Die Ziele vom Dashboard sind:
* Eine qualitative und schnelle Erfahrung für Benutzer
* Benutzerfreundliche UI, die auch von den dümmsten Usern benutzt werden kann
* gute Termin-einhaltende und funktionierende Arbeit
* Erleichterung von Informationen sammlung der Stationsleitern

== Anforderungen
- Anforderungen an die Applikationssoftware:
* Benutzerfreundliches Design und Datensicherheit für jeden User
* tolle Leistungserbringung und feste Robustheit
- Anforderungen an die Systemplattform:
* Eine Website, die klare Kommunikation zu Fehler besitzt und jederzeit verfügbar sein kann
* Es wird eine sehr hohe Leistung erwartet und Sicherheit wird sehr hohe Priorität haben
- Anbieter bezogene Anforderungen
* Das Projekt gewährleistet eine Pünktlichkeit auf der man sich immer vertrauen kann
* Die Projektorganisation wird stets zusammen bleiben und immer bereit für Kommunikation sein

== Mengengerüst
- Die zu erwartenden Datenmengen sind:
[cols="1,1"]
|===
|ID and Name of the Player
|The Time it took for them to finish
|The current Players Highscore
|The All Time Highscore
|The Data of previous races
|The currently connected Devices
|===

== Aufbau und Inhalt der Offerte
* Benutzerfreundliches UI mit Datensicherheit und Darstellung/Vergleichbarkeit von Informationen

== Administratives
- Das Projekt wird in einer Github Repository mit MIT-License verfügbar sein
- Der Budgetrahmen muss noch besprochen werden
- Bei Rückfragen zum Pflichtenheft sind wir immer offen
- Termine werden während dem Projektablauf dargestellt