= Pflichtenheft

== Beschreibung der Ausgangslage
- Die Ausgangssituation des Projektes ergibt sich aus der Herausforderung, dass Stationsleiter nicht in der Lage sind, alle Informationen zu allen Rennen in ihrem Gedächtnis zu behalten.

== Ist-Zustand
- Das Dashboard soll den Stationsleitern ermöglichen, schnell und einfach Informationen über die laufenden Rennen abzurufen.
- Die vorhandenen Systemplattformen werden die Personalcomputer der Stationsleiter sein.
- Das Dashboard wird live Informationen über eine Website streamen und den Stationsleitern ermöglichen, diese Informationen zu vergleichen.

== Zielsetzung
- Die Ziele vom Dashboard sind:
* Bereitstellung einer qualitativ hochwertigen und schnellen Benutzererfahrung.
* Entwicklung einer benutzerfreundlichen Benutzeroberfläche, die auch von unerfahrenen Benutzern intuitiv genutzt werden kann.
* Gewährleistung einer zuverlässigen und funktionellen Arbeitsweise.
* Vereinfachung der Informationsbeschaffung für die Stationsleiter.

== Anforderungen
- Anforderungen an die Applikationssoftware:
* Entwicklung einer benutzerfreundlichen Benutzeroberfläche mit hoher Datensicherheit für alle Benutzer
* Gewährleistung einer hohen Leistungsfähigkeit und Robustheit der Anwendung
- Anforderungen an die Systemplattform:
* Einrichtung einer Website mit klaren Fehlerkommunikationen und kontinuierlicher Verfügbarkeit.
* Sicherstellung einer hohen Leistungsfähigkeit und Priorisierung der Datensicherheit
- Anbieter bezogene Anforderungen
* Garantie der Pünktlichkeit und Zuverlässigkeit des Projekts.
* Aufrechterhaltung einer effektiven Projektorganisation und offener Kommunikation

== Mengengerüst
- Die zu erwartenden Datenmengen sind:
[cols="1,1"]
|===
|Players: 2
|The All Time Highscore: 10000
|The currently connected Devices: 5
|The Devices used in the race: 5
|API Calls to Database: 20
|===

== Aufbau und Inhalt der Offerte
* Entwicklung einer benutzerfreundlichen Benutzeroberfläche mit hoher Datensicherheit und einfachem Zugang zu Renninformationen.

== Administratives
- Das Projekt wird in einem GitHub-Repository unter der MIT-Lizenz verfügbar sein.
- Der Budgetrahmen muss noch festgelegt werden und wird im weiteren Verlauf diskutiert.
- Bei Fragen zum Pflichtenheft stehen wir jederzeit zur Verfügung.
- Die Termine werden während des Projektverlaufs transparent dargestellt und eingehalten.