= Projektantrag / Projektauftrag

=== Projektbezeichnung
Robodashboard

=== Projektauftraggeber
Herbert Aitenbichler

== Projekthintergrund
- Ein Überblick erschaffen für die Stationsmanager über die Rennen.


== Projektergebnis
- Eine funktionierende Applikation, die es den Stationsmanager die Informationssammlung erleichtert.
- Die messbaren Eigenschaften sind: eine Kontrolle über die Informationen von einem Rennen.

== Projektziele
- Das Ziel des Projektes ist eine vollständige und funktionierende Desktop-App, die den Stationsmanager Informationen über das Rennen gibt..

== Projektbeschreibung
- Projekthauptaufgaben: Live Updating von Informationen, Einfügen von neuen Datensätzen, Vergleich zwischen Daten

== Meilensteine
- Grundlegende Dokumentation und Spezifikation fertigstellung
- Projektenvironment aufstellen
- Prototype Erstellung
- Design der Website ist teilweise implementiert
(Buttons und Funktionalitäten noch nicht funktionsfähig/darstellbar)
- Anzeige der verbundenen Controller und Spieler
- Rennen können gespeichert, aktualisiert und angezeigt werden
- Anzeige und Aktualisierung von Highscore
- Finale Quality of Life changes und Vollendung der Logikimplementierung
- Testphase
- Freistellung

==== Projektstart
- 7.2.2024

==== Projektende
- 5.7.2024

==== Projektressourcen
- Computerhardware, Teammitglieder

==== Projektrisiken
- Kostenüberschreitungen, minderwertige Arbeit, Verzögerungen aufgrund unvorhergesehene technische Probleme

==== Projektorganisation
Projektteam - Vincent Tea, Stefan Alesi

==== Abschluss des Projektauftrags
- 7.2.2024